/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Entidades.*;
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.JOptionPane;

/**
 *
 * @author Estudiante
 */
public class EditarSmartTV extends javax.swing.JFrame {

    /**
     * Creates new form EditarSmartTV
     */
    SmartTv smart;
    ListaDeNavegadores padre;
    public EditarSmartTV(ListaDeNavegadores padre) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.padre = padre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        cbxPuerto = new javax.swing.JComboBox<>();
        lblconexion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setBackground(new java.awt.Color(204, 36, 36));
        btnVolver.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 106, -1));

        btnguardar.setBackground(new java.awt.Color(0, 135, 0));
        btnguardar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar SmartTV");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marca ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modelo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtmarca.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 180, -1));

        txtmodelo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(txtmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 180, -1));

        cbxPuerto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cbxPuerto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HDMI", "VGA", "DVI", "DisplayPort", "RCA", "Signal", "S-Video", "Coaxial", " " }));
        jPanel1.add(cbxPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        lblconexion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblconexion.setForeground(new java.awt.Color(255, 255, 255));
        lblconexion.setText("Tipo de Conexion");
        jPanel1.add(lblconexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        String marca = txtmarca.getText();
        String modelo = txtmodelo.getText();
        int tipo =  cbxPuerto.getSelectedIndex();
        
        if(!"".equals(marca)&&!"".equals(modelo)&&!"".equals(tipo)){
            if(JOptionPane.showConfirmDialog(this,"¿Deseas Guardar?")==
                    JOptionPane.OK_OPTION){
                smart = new SmartTv();
                smart.setMarca(marca);
                smart.setModelo(modelo);       
                smart.setTipoConexion(tipo);
                padre.addSmartTV(smart);
                this.setVisible(false);
                this.dispose();
                padre.actualizarLista();
                padre.setVisible(true);

            }
                    }else{
            JOptionPane.showMessageDialog(rootPane, "Complete todos los campos"
                    ,"Agregar Celular", HEIGHT);
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        this.dispose();
        padre.actualizarLista();
        padre.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cbxPuerto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblconexion;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    // End of variables declaration//GEN-END:variables
}
